"""
SVG and PNG export utilities for img2plot vector drawings.
Supports physical page dimensions, margins, pen width, and multi-layer SVG groups.
"""

from __future__ import annotations
import math
import os
from typing import List, Tuple, Optional
from PIL import Image, ImageDraw

from .parameters import PlotParameters
from .engine import StrokePath, EngineResult
from .bezier import discretize_segments


PAGE_SIZES_MM = {
    "A4": (210.0, 297.0),
    "A3": (297.0, 420.0),
    "A5": (148.0, 210.0),
    "Letter": (215.9, 279.4),
}


def export_svg(
    result: EngineResult,
    params: PlotParameters,
    output_path: str
) -> None:
    """
    Export vectorized paths to an SVG file optimized for pen plotters and vector graphics.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    img_w = float(result.width)
    img_h = float(result.height)
    aspect = img_w / max(1.0, img_h)

    # Calculate page size in mm
    if params.page_format in PAGE_SIZES_MM:
        pw, ph = PAGE_SIZES_MM[params.page_format]
        # Orient page to match aspect ratio
        if (aspect > 1.0 and pw < ph) or (aspect < 1.0 and pw > ph):
            pw, ph = ph, pw
    elif params.page_format == "Custom":
        pw = params.page_width_mm
        ph = params.page_height_mm
    else:  # "Original"
        # 96 DPI: 1 px ~ 0.264583 mm
        pw = img_w * 0.264583
        ph = img_h * 0.264583

    margin = params.margin_mm if params.page_format != "Original" else 0.0
    drawable_w = max(1.0, pw - 2.0 * margin)
    drawable_h = max(1.0, ph - 2.0 * margin)

    # Scale to fit inside drawable area preserving aspect ratio
    scale = min(drawable_w / img_w, drawable_h / img_h)
    target_w = img_w * scale
    target_h = img_h * scale

    # Center on page
    offset_x = margin + (drawable_w - target_w) / 2.0
    offset_y = margin + (drawable_h - target_h) / 2.0

    stroke_col = params.stroke_color
    stroke_w_mm = params.stroke_width_mm

    svg_lines: List[str] = [
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{pw:.2f}mm" height="{ph:.2f}mm" viewBox="0 0 {pw:.2f} {ph:.2f}" '
        f'version="1.1">',
        '  <desc>Generated by img2plot (Python Vectorizer)</desc>',
        f'  <!-- Layer 1: Contours and Main Edges -->',
        f'  <g id="layer_contours" stroke="{stroke_col}" stroke-width="{stroke_w_mm:.3f}mm" '
        f'fill="none" stroke-linecap="round" stroke-linejoin="round">',
    ]

    hatch_lines: List[str] = [
        f'  <!-- Layer 2: Hatching and Shadows -->',
        f'  <g id="layer_hatching" stroke="{stroke_col}" stroke-width="{stroke_w_mm * 0.85:.3f}mm" '
        f'fill="none" stroke-linecap="round" stroke-linejoin="round">',
    ]

    def transform_pt(x: float, y: float) -> Tuple[float, float]:
        return (offset_x + x * scale, offset_y + y * scale)

    for path in result.paths:
        if path.is_bezier and path.cubic_segments:
            # Transform cubic segments
            segs_str = []
            p1_x, p1_y = transform_pt(*path.cubic_segments[0][0])
            segs_str.append(f"M {p1_x:.3f},{p1_y:.3f}")

            for _, c1, c2, p2 in path.cubic_segments:
                c1_t = transform_pt(*c1)
                c2_t = transform_pt(*c2)
                p2_t = transform_pt(*p2)
                segs_str.append(
                    f"C {c1_t[0]:.3f},{c1_t[1]:.3f} {c2_t[0]:.3f},{c2_t[1]:.3f} {p2_t[0]:.3f},{p2_t[1]:.3f}"
                )
            d = " ".join(segs_str)
        else:
            p_start = transform_pt(*path.points[0])
            p_end = transform_pt(*path.points[-1])
            d = f"M {p_start[0]:.3f},{p_start[1]:.3f} L {p_end[0]:.3f},{p_end[1]:.3f}"

        path_tag = f'    <path d="{d}" />'
        if path.is_hatch:
            hatch_lines.append(path_tag)
        else:
            svg_lines.append(path_tag)

    svg_lines.append('  </g>')
    hatch_lines.append('  </g>')

    svg_lines.extend(hatch_lines)
    svg_lines.append('</svg>\n')

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(svg_lines))


def export_png(
    result: EngineResult,
    params: PlotParameters,
    output_path: str,
    bg_color: str = "white",
    scale_factor: float = 2.0,
) -> None:
    """
    Render vector paths to a high-resolution raster PNG image.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    w = int(result.width * scale_factor)
    h = int(result.height * scale_factor)

    canvas = Image.new("RGBA", (w, h), (255, 255, 255, 255) if bg_color == "white" else (0, 0, 0, 0))
    draw = ImageDraw.Draw(canvas)

    line_color = params.stroke_color
    line_width = max(1, int(round(params.stroke_width_mm * 2.5 * scale_factor)))

    for path in result.paths:
        if path.is_bezier and path.cubic_segments:
            pts = discretize_segments(path.cubic_segments, steps_per_segment=6)
        else:
            pts = path.points

        if len(pts) >= 2:
            scaled_pts = [(p[0] * scale_factor, p[1] * scale_factor) for p in pts]
            draw.line(scaled_pts, fill=line_color, width=line_width, joint="curve")

    canvas.save(output_path, "PNG")
